basePath: /
info:
  contact: {}
  description: Query-Service backend api documents
  title: Query-Service Backend Api
  version: "1.0"
paths:
  /user-accounts/{id}:
    get:
      parameters:
      - description: User Account ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "201":
          description: '{"success":true,"data":"","msg":"Success"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get User Account
      tags:
      - UserAccountApi
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
