// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user-accounts": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "UserAccountApi"
                ],
                "summary": "Create User Account",
                "parameters": [
                    {
                        "description": "CreateUserAccount DTO",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserAccountDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"success\":true,\"msg\":\"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-accounts/draw": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "UserAccountApi"
                ],
                "summary": "Draw Money from User Account",
                "parameters": [
                    {
                        "description": "To Draw Money DTO",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ToDrawMoneyDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"msg\":\"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-accounts/invest": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "UserAccountApi"
                ],
                "summary": "Invest Money to User Account",
                "parameters": [
                    {
                        "description": "To Invest Money DTO",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ToInvestMoneyDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"msg\":\"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateUserAccountDTO": {
            "type": "object",
            "required": [
                "account_number",
                "name",
                "sur_name",
                "tckno"
            ],
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sur_name": {
                    "type": "string"
                },
                "tckno": {
                    "type": "string"
                }
            }
        },
        "dto.ToDrawMoneyDTO": {
            "type": "object",
            "required": [
                "account_number",
                "amount"
            ],
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "currency_type": {
                    "type": "string"
                }
            }
        },
        "dto.ToInvestMoneyDTO": {
            "type": "object",
            "required": [
                "account_number",
                "amount"
            ],
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "currency_type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Command-Service Backend Api",
	Description: "Command-Service backend api documents",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
